<div class="superHeader">
  <div class="left">
    <a href="http://rc.jeremdow.com">home</a>
    <a href="http://blog.jeremdow.com">blog</a>
    <a href="http://profiles.google.com/jeremdow">profile</a>
    <a href="http://flickr.com/jeremdow" target="blank">flickr</a>
    <a href="http://facebook.com/jeremdow" target="blank">facebook</a>
    <a href="http://twitter.com/jeremdow" target="blank">twitter</a>
    <a href="http://git.jeremdow.com">git</a>
  </div>

  <div class="right">
    <span class="doNotDisplay">Related links:</span>
    <a href="http://git.jeremdow.com/?p=jeremdow.com.git;a=summary">site updates</a>
    | <a href="/sitemap">site map</a>
  </div>
</div>
