<div id="feed">
  <p>
    <!-- <a href="http://fusion.google.com/add?source=atgs&feedurl=http%3A//jeremdow.com/blog/index.rss"><img src="http://buttons.googlesyndication.com/fusion/add.gif" border="0" alt="Add to Google"></a> -->
    <a class="feed" target="blank" href="http://jeremdow.us/blog/index.rss"><img alt="RSS" src="http://jeremdow.us/_images/feed-icon16x16.png" /></a>
  </p>
</div>
<div id="footer">
  <br class="doNotDisplay doNotPrint" />

  <div class="right">
    <p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
      2006-2012 <a rel="dct:publisher" href="http://jeremdow.us">Jeremiah Dow</a> | <a rel="license" href="http://creativecommons.org/publicdomain/zero/1.0/">CC0</a>
    </p>
  </div>

  <div class="left">
    <p>
      <a href="http://werc.cat-v.org/" target="blank">Powered by werc</a>
    </p>
  </div>
</div>
