<div id="feed">
  <p>
    <a class="feed" target="blank" href="https://jeremdow.us/blog/index.rss"><img alt="RSS" src="https://jeremdow.us/_images/feed-icon16x16.png" /></a>
  </p>
</div>
<div id="footer">
  <br class="doNotDisplay doNotPrint" />

  <div class="right">
    <p xmlns:dct="https://purl.org/dc/terms/" xmlns:vcard="https://www.w3.org/2001/vcard-rdf/3.0#">
      2006-2016 <a rel="dct:publisher" href="https://jeremdow.us">Jeremiah Dow</a> | <a rel="license" href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>
    </p>
  </div>

  <div class="left">
    <p>
      <a href="https://werc.cat-v.org/" target="blank">Powered by werc</a>
    </p>
  </div>
</div>
