<nav class="superHeader">
  <div class="left">
    <a href="http://profiles.google.com/jeremdow">+Jeremiah</a>
    <a href="http://jeremdow.us" class="thisPage">About</a>
    <a href="http://jeremdow.com/us">Blog</a>
    <a href="http://profiles.google.com/jeremdow/photos" target="blank">Photos</a>
    <a href="http://facebook.com/jeremdow" target="blank">Facebook</a>
    <a href="http://twitter.com/jeremdow" target="blank">Twitter</a>
    <a href="http://git.jeremdow.us">Git</a>
  </div>

  <div class="right">
    <span class="doNotDisplay">Related links:</span>
    <a href="http://git.jeremdow.com/?p=jeremdow.us.git;a=summary">site updates</a>
    | <a href="/sitemap">site map</a>
  </div>
</nav>
