<nav class="superHeader">
  <div class="left">
    <a href="https://plus.google.com/+JeremiahDow/about" target="blank">+JeremiahDow</a>
    <a href="https://jeremdow.us" class="thisPage">About</a>
    <a href="https://jeremdow.us/blog">Blog</a>
    <a href="https://plus.google.com/+JeremiahDow/photos" target="blank">Photos</a>
    <a href="https://facebook.com/jeremdow" target="blank">Facebook</a>
    <a href="https://twitter.com/jeremdow" target="blank">Twitter</a>
    <a href="https://github.com/jeremdow">Git</a>
  </div>

  <div class="right">
    <span class="doNotDisplay">Related links:</span>
    <a href="https://github.com/jeremdow/werc/commits/master">site updates</a>
    | <a href="/sitemap">site map</a>
  </div>
</nav>
