<nav class="superHeader">
  <div class="left">
    <a href="http://plus.google.com/+JeremiahDow/about" target="blank">+JeremiahDow</a>
    <a href="http://jeremdow.us" class="thisPage">About</a>
    <a href="http://jeremdow.us/blog">Blog</a>
    <a href="http://plus.google.com/+JeremiahDow/photos" target="blank">Photos</a>
    <a href="http://facebook.com/jeremdow" target="blank">Facebook</a>
    <a href="http://twitter.com/jeremdow" target="blank">Twitter</a>
    <a href="http://git.jeremdow.us">Git</a>
  </div>

  <div class="right">
    <span class="doNotDisplay">Related links:</span>
    <a href="http://git.jeremdow.us/?p=jeremdow.us.git;a=summary">site updates</a>
    | <a href="/sitemap">site map</a>
  </div>
</nav>
