<link rel="alternate" type="application/atom+xml" title="ATOM" href="http://blog.jeremdow.com/index.atom">
<link rel="alternate" type="application/rss+xml" title="RSS" href="http://blog.jeremdow.com/index.rss">

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22084762-1']);
  _gaq.push(['_setDomainName', '.jeremdow.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
