<div id="feed">
  <p>
    <a class="feed" target="blank" href="http://feeds.feedburner.com/jeremdow"><img alt="Subscribe in a reader" src="http://jeremdow.com/_images/feed-icon16x16.png" /></a>
  </p>
</div>
<div id="footer">
  <br class="doNotDisplay doNotPrint" />

  <div class="right">
    <p>
      &copy; 2006-2011 Jeremiah Dow | <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA</a>
    </p>
  </div>

  <div class="left">
    <p>
      <a href="http://werc.cat-v.org/" target="blank">Powered by werc</a>
    </p>
  </div>
</div>
