<nav class="superHeader">
  <div class="left">
    <a href="http://profiles.google.com/jeremdow">+Jeremiah</a>
    <a href="http://jeremdow.com">About</a>
    <a href="http://blog.jeremdow.com" class="thisPage">Blog</a>
    <a href="http://flickr.com/jeremdow" target="blank">Flickr</a>
    <a href="http://facebook.com/jeremdow" target="blank">Facebook</a>
    <a href="http://twitter.com/jeremdow" target="blank">Twitter</a>
    <a href="http://git.jeremdow.com">Git</a>
  </div>

  <div class="right">
    <span class="doNotDisplay">Related links:</span>
    <a href="http://git.jeremdow.com/?p=jeremdow.com.git;a=summary">site updates</a>
    | <a href="/sitemap">site map</a>
  </div>
</nav>
